name: Extract, repackage and publish images for cert-manager

on:
  push:
    branches:
      - main
    # paths:
    #   - 'upstream/cert-manager'

permissions:
  packages: write
  contents: read

jobs:
  relocate-images:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        echo "Logged into Github Packages: ${{ github.actor }}"

    - name: Set up Carvel tools
      uses: carvel-dev/setup-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        only: kbld, imgpkg

    - name: Build and relocate images
      run: |
        kbld -f upstream/cert-manager/cert-manager.yaml --imgpkg-lock-output cluster/cert-manager/images.lock.yaml > cluster/cert-manager/cert-manager-output.yaml
        echo "-------"
        echo "images.lock.yaml:"
        echo "-------"
        cat cluster/cert-manager/images.lock.yaml
        echo "-------"
        imgpkg copy --lock cluster/cert-manager/images.lock.yaml --lock-output cluster/cert-manager/ghcr.lock.yaml --to-repo ghcr.io/${{ github.repository }}
        echo "Saving packages to: ${{ github.repository }}"
